version: "3.8"

volumes:
  clickhouse_data:

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    env_file:
      - ./.env_files/clickhouse.env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${DW_CLICKHOUSE_HTTP_PORT:-8123}:8123
      - ${DW_CLICKHOUSE_NATIVE_PORT:-9000}:9000
      - ${DW_CLICKHOUSE_POSTGRES_PORT:-9005}:9005
    volumes:
      - ./clickhouse-server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./clickhouse-server/config.d/override.yml:/etc/clickhouse-server/config.d/override.yml:ro
      - ./clickhouse-server/users.d/override.yml:/etc/clickhouse-server/users.d/override.yml:ro
      - ./scripts:/scripts:ro
      - clickhouse_data:/var/lib/clickhouse:rw
    healthcheck:
      test: wget --no-verbose --spider http://localhost:8123/ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
